[[plugins]]
# neosnippet
repo = 'Shougo/neosnippet.vim'
hook_source = '''
  "Ctrl+Kにターゲットジャンプ割当
  imap <C-i> <Plug>(neosnippet_expand_or_jump)
  smap <C-i> <Plug>(neosnippet_expand_or_jump)
  xmap <C-i> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']

[[plugins]]
# deoplete
# 補完
repo = 'Shougo/neocomplete.vim'
hook_source = '''
  " Vim起動時にneocompleteを有効にする
  let g:neocomplete#enable_at_startup = 1
  " smartcase有効化. 大文字が入力されるまで大文字小文字の区別を無視する
  let g:neocomplete#enable_smart_case = 1
  " 補完を取り消し
  inoremap <expr><C-g>     neocomplete#undo_completion()
  " 補完候補の共通部分を補完
  inoremap <expr><C-l>     neocomplete#complete_common_string()
'''
on_i = 1

[[plugins]]
# pythonの補完
repo = "davidhalter/jedi-vim"
hook_source = '''
  autocmd FileType python setlocal completeopt-=preview " pydocを非表示
'''
on_ft = ['python']

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
# lexima
# 括弧補完
repo = 'cohama/lexima.vim'
on_i = 1
